### ISSUE TITLE
Fetch anime started could do more than return the state, yh?

### ISSUE THREAD

**Issue by ooade** [Oluwaseunus/anime-characters#7]
https://github.com/Oluwaseunus/anime-characters/blob/4cf0168c6477e00e80955179d3fcfeaca4328478/src/reducers/animes.js#L8

This relates to #6. What can be done? Besides, you still don't have to change anything.

**Comment by Oluwaseunus** [comment]
It was mostly supposed to be an initializer for a loading state. i.e., if the 'loading' state would be managed by redux, this action would be dispatched, setting the state to loading, and the Main component would read the loading state from the redux store and use that to decide whether or not to show the loading screen.

**Comment by ooade** [comment]
Yeah, you could change the loading state from there and control the loader that way. Cool.
